files:
  - source: /app/src/main/res/values/metrolist_strings.xml
    translation: /app/src/main/res/values-%android_code%/metrolist_strings.xml
    languages_mapping:
      android_code:
        af: af
        ar: ar
        az: az
        be: be
        bg: bg
        bn: bn
        bs: bs
        ca: ca
        cs: cs
        de: de
        el: el
        es-ES: es
        es-US: es-rUS
        et: et
        eu: eu
        fa: fa
        fi: fi
        fil: fil
        fr: fr
        gl: gl
        hi: hi
        hr: hr
        hu: hu
        id: in
        it: it
        he: iw
        ja: ja
        ko: ko
        lt: lt
        ml: ml
        ms: ms
        no: nb-rNO
        nl: nl
        nn-NO: nn
        pa-IN: pa
        pl: pl
        pt-PT: pt
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sq: sq
        sr: b+sr+Latn
        ta: ta
        te: te
        th: th
        tr: tr
        uk: uk
        vi: vi
